; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppId={{5B1C0293-8750-4058-8885-F0FDE9D348BD}
AppName=VR Charging Status
AppVersion=1.5
AppPublisher=NepNep, Inc.
DefaultDirName={autopf}\VR Charging Status
UninstallDisplayIcon={app}\VR Charging Status.exe
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
OutputBaseFilename=vrcssetup
SetupIconFile=I:\Users\OwO\Desktop\watertracker\assets\caticon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "I:\Users\OwO\Desktop\dem\charging notifier\dist\VR Charging Status.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\VR Charging Status"; Filename: "{app}\VR Charging Status.exe"
Name: "{autodesktop}\VR Charging Status"; Filename: "{app}\VR Charging Status.exe"; Tasks: desktopicon
Name: "{startup}\VR Charging Status"; Filename: "{app}\VR Charging Status.exe"; Parameters: "--minimized"

[Run]
Filename: "{app}\VR Charging Status.exe"; Description: "{cm:LaunchProgram,VR Charging Status}"; Flags: nowait postinstall skipifsilent


